const POINTS_MINOR = 20
const POINTS_MAJOR = 30
const DOUBLED_BASE_VALUE = 50
const UNDERTRICK_BASE_VALUE = 50
const UNDERTRICK_DOUBLED_LOOKUP = [100, 200, 200, 300]
const UNDERTRICK_DOUBLED_VULNERABLE_LOOKUP = [200, 300]

export {
  POINTS_MINOR,
  POINTS_MAJOR,
  DOUBLED_BASE_VALUE,
  UNDERTRICK_BASE_VALUE,
  UNDERTRICK_DOUBLED_LOOKUP,
  UNDERTRICK_DOUBLED_VULNERABLE_LOOKUP
}
