const POINTS_MINOR = 20
const POINTS_MAJOR = 30
const DOUBLED_BASE_VALUE = 50
const UNDERTRICK_BASE_VALUE = 50
const UNDERTRICK_DOUBLED_LOOKUP = [100, 200, 200, 300]
const UNDERTRICK_DOUBLED_VULNERABLE_LOOKUP = [200, 300]
const SLOW_RUBBER_BONUS = 500
const FAST_RUBBER_BONUS = 750
const SS_BONUS_BASE_VALUE = 500
const GS_BONUS_BASE_VALUE = 1000

export {
  POINTS_MINOR,
  POINTS_MAJOR,
  DOUBLED_BASE_VALUE,
  UNDERTRICK_BASE_VALUE,
  UNDERTRICK_DOUBLED_LOOKUP,
  UNDERTRICK_DOUBLED_VULNERABLE_LOOKUP,
  SLOW_RUBBER_BONUS,
  FAST_RUBBER_BONUS,
  SS_BONUS_BASE_VALUE,
  GS_BONUS_BASE_VALUE
}
